[phases.setup]
nixPkgs = ["python311"]   # was python313

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"   # was 3.13
